
GET http://127.0.0.1:8000/api/books HTTP/1.1
###
POST http://127.0.0.1:8000/api/books HTTP/1.1

Content-Type: application/json

{
    "id":4,
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "description":"The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
}